(in-package :cl-user)

(defun udp-echo-test (port)
  (let ((server (comm:start-udp-server :service port))
        (stream (comm:open-udp-stream "localhost" port))
        (data "Hello, World!"))
    (dotimes (i 10)
      (format stream "~S~%" data)
      (force-output stream)
      (format t "~D: Send message: ~A~%" i data)
      (let ((echo (read-line stream)))
        (format t "~D: Recv message: ~A~%" i echo)))
    (close stream)
    (comm:stop-udp-server server)))
